name: "Orb"
description: "Orb sensor to continuously monitor network responsiveness and reliability."
version: "0.12.35"
slug: "orb_homeassistant"
init: false
host_network: true
image: "orbforge/orb"
environment:
 ORB_DATA_DIR: /data
arch:
  - aarch64
  - amd64
  - armv7
boot: auto
options: {}
schema: {}
